CREATE TABLE `Server` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`CPU` INT NOT NULL,
	`RAM` INT NOT NULL,
	`SSD` INT NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `Client` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`FIO` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`hashPassword` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `Order` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`idClient` INT NOT NULL,
	`idServer` INT NOT NULL,
	`dateTimeStart` DATETIME NOT NULL,
	`dateTimeEnd` DATETIME NOT NULL,
	`price` DECIMAL NOT NULL,
	`RAM` INT NOT NULL,
	`CPU` INT NOT NULL,
	`SSD` INT NOT NULL,
	`OS` VARCHAR(255) NOT NULL,
	`ipAdress` INT NOT NULL,
	PRIMARY KEY (`id`)
);

ALTER TABLE `Order` ADD CONSTRAINT `Order_fk0` FOREIGN KEY (`idClient`) REFERENCES `Client`(`id`);

ALTER TABLE `Order` ADD CONSTRAINT `Order_fk1` FOREIGN KEY (`idServer`) REFERENCES `Server`(`id`);




